### ISSUE TITLE
M1 MacBook can not use this instead of dosbox

### ISSUE THREAD

**Issue by lingyy-1109** [dosasm/vscode-dosbox#1]
when I try to compile and run a .asm document with MASM/TASM, there is an error like this:
![image](https://user-images.githubusercontent.com/57227294/140675138-9fe452d0-ef29-4eb5-a335-a5ee1c2c36de.png)
I don't know how to deal with that.

**Comment by lingyy-1109** [comment]
I've solved this question by `brew install dosbox` but the dosbox interface is a little bit wired. I want to know why.
![image](https://user-images.githubusercontent.com/57227294/140677351-c81684fe-c05f-40a7-bf63-5cb71461f6a7.png)

**Comment by xsro** [comment]
Hello, Thanks for your issue.

I think this is caused by the dosbox 's opengl.

```
[sdl]
output=opengl
```

A workaround is change its config file in /Users/***Your username***/Library/Preferences/DOSBox 0.74-3 Preferences. and set `output` as `surface`.

- Note1: There are some bug in the extension and soon we will be able to overwrite some in the extension setting
- Note2: use command `dosbox -printconf` for your path of dosbox conf
